User.create!([
  {name: "John", email: "John@gmail.com", password_digest: "$2a$10$a0Er4OzlDIVS/1mdev66N.bOLMe7QkWy4NvNAmhqs92IR1nnOHHLm"},
  {name: "luke", email: "luke@gmail.com", password_digest: "$2a$10$i9tfpTEBi/hIc6DrHdq93uz9uVDe9XTchOpBQEeCMibxm/nAE8o5S"},
  {name: "George", email: "George@gmail.com", password_digest: "$2a$10$D0.c2a8D4Xfak0gzSLYL1OfES./fuWuM4IvkmYbmwvalaCLUz2Xcm"},
  {name: "Chris", email: "Chris@gmail.com", password_digest: "$2a$10$yAQ.SdLbWMScaQZiHak/m.PmR4fhJSVO6PD4J33mSRw3tKk0k9jrm"},
  {name: "Russell", email: "russ@test.com", password_digest: "$2a$10$QOcK/Uwp3wmWEpMc3fYul.SlXD5pE.7UyFCOF1aMKPhVbKd6B.FJW"}
])

Car.create!([
  {make: "defaultsls.obj", model: "Mercedes SLS", year: "2016", image: "http://eskipaper.com/images/mercedes-sls-2.jpg", default_color: "defaultsls.mtl", color_one: "redsls.mtl", color_two: nil, color_three: nil, color_four: nil, color_five: nil},
  {make: "defaultlaferrari.obj", model: "LaFerrari", year: "2014", image: "http://tcledev.com/wp-content/uploads/2015/08/2014-Ferrari-LaFerrari-Best-Photoshoot.jpg", default_color: "defaultlaferrari.mtl", color_one: nil, color_two: nil, color_three: nil, color_four: nil, color_five: nil},
  {make: "defaultspider.obj", model: "Ferrari Spider", year: "2013", image: "http://www.victorymusclecars.com/VMC/wp-content/gallery/2013-ferrari-458-spider/ferrari-458_spider_2013_02.jpg", default_color: "defaultspider.mtl", color_one: "tealspider.mtl", color_two: nil, color_three: nil, color_four: nil, color_five: nil},
  {make: "avent.obj", model: "Aventador", year: "2016", image: "https://www.lamborghini.com/en-en/sites/en-en/files/DAM/lamborghini/model/aventador/aventador-s/header/aventador-s-header.jpg", default_color: "defaultavent.mtl", color_one: "greenavent.mtl", color_two: "purpleavent.mtl", color_three: "redavent.mtl", color_four: "tealavent.mtl", color_five: nil}
])

Customization.create!([
  {color: "purpleavent.mtl", wheels: "22", rims: "alloy", car_id: 3, user_id: 2},
  {color: "greenavent.mtl", wheels: "22", rims: "steel", car_id: 3, user_id: 1},
  {color: "tealavent.mtl", wheels: "21", rims: "plastic", car_id: 3, user_id: 3},
  {color: "redsls.mtl", wheels: "19", rims: "alloy", car_id: 2, user_id: 4},
  {color: "greenavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "purpleavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "purpleavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "redavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "purpleavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "purpleavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "purpleavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "redavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "greenavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "redavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "22", rims: "22", car_id: 3, user_id: 5},
  {color: "purpleavent.mtl", wheels: "22", rims: "22", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "22", rims: "22", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "22", rims: "32", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5},
  {color: "tealavent.mtl", wheels: "", rims: "", car_id: 3, user_id: 5}
])

Comment.create!([
  {comment: "Amazing!", customization_id: 6, user_id: 1},
  {comment: "Woah!", customization_id: 14, user_id: 1},
  {comment: "Sick!", customization_id: 2, user_id: 1},
  {comment: "Nice!", customization_id: 10, user_id: 1},
  {comment: "Nice!", customization_id: 4, user_id: 1},
  {comment: "Woah!", customization_id: 12, user_id: 1},
  {comment: "Woah!", customization_id: 2, user_id: 1},
  {comment: "Amazing!", customization_id: 11, user_id: 1},
  {comment: "Nice!", customization_id: 8, user_id: 1},
  {comment: "Sick!", customization_id: 11, user_id: 1},
  {comment: "Sick!", customization_id: 3, user_id: 2},
  {comment: "Sick!", customization_id: 7, user_id: 2},
  {comment: "Amazing!", customization_id: 9, user_id: 2},
  {comment: "Sick!", customization_id: 9, user_id: 2},
  {comment: "Sick!", customization_id: 5, user_id: 2},
  {comment: "Woah!", customization_id: 15, user_id: 3},
  {comment: "Woah!", customization_id: 4, user_id: 3},
  {comment: "Woah!", customization_id: 5, user_id: 3},
  {comment: "Amazing!", customization_id: 12, user_id: 3},
  {comment: "Amazing!", customization_id: 5, user_id: 3},
  {comment: "Amazing!", customization_id: 3, user_id: 4},
  {comment: "Amazing!", customization_id: 10, user_id: 4},
  {comment: "Nice!", customization_id: 9, user_id: 4},
  {comment: "Amazing!", customization_id: 3, user_id: 4},
  {comment: "Amazing!", customization_id: 2, user_id: 4},
  {comment: "Amazing!", customization_id: 10, user_id: 5},
  {comment: "Sick!", customization_id: 14, user_id: 5},
  {comment: "Woah!", customization_id: 5, user_id: 5},
  {comment: "Nice!", customization_id: 5, user_id: 5},
  {comment: "Amazing!", customization_id: 15, user_id: 5},
  {comment: "Nice!", customization_id: 1, user_id: 5},
  {comment: "Nice!", customization_id: 3, user_id: 5}
])

Vote.create!([
  {value: 1, customization_id: 12, user_id: 1},
  {value: 1, customization_id: 7, user_id: 1},
  {value: 1, customization_id: 8, user_id: 1},
  {value: -1, customization_id: 12, user_id: 1},
  {value: -1, customization_id: 15, user_id: 1},
  {value: -1, customization_id: 3, user_id: 1},
  {value: -1, customization_id: 16, user_id: 2},
  {value: -1, customization_id: 16, user_id: 2},
  {value: -1, customization_id: 1, user_id: 2},
  {value: 1, customization_id: 3, user_id: 2},
  {value: 1, customization_id: 9, user_id: 2},
  {value: 1, customization_id: 15, user_id: 3},
  {value: 1, customization_id: 11, user_id: 3},
  {value: -1, customization_id: 13, user_id: 3},
  {value: 1, customization_id: 2, user_id: 3},
  {value: 1, customization_id: 16, user_id: 3},
  {value: 1, customization_id: 7, user_id: 4},
  {value: 1, customization_id: 12, user_id: 4},
  {value: -1, customization_id: 5, user_id: 4},
  {value: -1, customization_id: 1, user_id: 4},
  {value: 1, customization_id: 9, user_id: 4},
  {value: -1, customization_id: 3, user_id: 5},
  {value: 1, customization_id: 13, user_id: 5},
  {value: -1, customization_id: 9, user_id: 5},
  {value: -1, customization_id: 4, user_id: 5},
  {value: -1, customization_id: 9, user_id: 5}
])
